In [3]:
import numpy as np
import numpy.linalg as la
import scipy.io as sio
import matplotlib.pyplot as plt

## Rechnerunterstützte Mechanik I Wintersemester 2017/18
# Übung 9: Numerische Integration
## Inhalt: Gauss-Quadratur


In [4]:
print('Testat zur 9. Übung zur Vorlesung Rechnerunterstützte Mechanik I')
omega = 13.6753
PI    = np.arccos(-1)
Tmin  = 0
Tmax  = 0.5*PI
funk  = lambda x: np.sin(omega*x)

Testat zur 9. Übung zur Vorlesung Rechnerunterstützte Mechanik I


### Exakter Wert des Integrals:

In [5]:
Iexakt = (-1/omega)*(np.cos(omega*Tmax) - np.cos(omega*Tmin))
print("Iexakt = ", Iexakt)

Iexakt =  0.136942236552


### IntegratePolynomial

In [20]:
def IntegratePolynomial( p, a, b ):
    result = 0.0
    
    for i in range(len(p)):
        val = p[i] * ( (1/(i+1)) * (b**(i+1) - a**(i+1)))
        result = result + val 
    
    return result

### Gauss-Christoffel-Quadratur:

In [37]:
print('Gauss-Quadratur')
### Wie viele Koeffizienten sollen berechnet werden?
maxorder = 10
N        = maxorder
Legendre = np.zeros([N + 1, N + 1])
Nst      = np.zeros([N + 1, N + 1]) ### Dim=Ordnung + 1

### Berechnung der Legendre-Polynome 1...maxorder+1:
### (die NST des N+1-ten Polynoms liefern die Stuetzstellen
### fuer das Verfahren der Ordnung N)
for i in range(0,N+1):
    # Koeffizienten alpha ausrechnen:
    alpha = np.zeros(i)
      ### Berechnung der Koeffizienten:
    for j in range(0,i):
        print("i={} j={}".format(i,j))
        q = np.zeros(2*i) ### Ausreichend Speicher reservieren
        ### Shift right: (q entspricht: Legendre_j * t^(i-1) )
        ### Python:       q entspricht: Legendre_j * t^i
        print("q[{}:{}] = Legendreteil:".format(i,i+j), Legendre[j][0:j])
        q[i:i+j] = Legendre[j][0:j]
        ### Berechne t^(i-1)*Legendre_j
        ### Python:  t^i    *Legendre_j 
        alpha[j]   = IntegratePolynomial(q, a=0, b=1)
        print("alpha = ", alpha)
    
    ### Jetzt muss ausgehend von p=t^(i-1) das Legendre-Polynom
    ###                          p=t^i
    ### aufgestellt werden
    Legendre[i,i] = 1
    print(alpha)
    for j in range(0,i-1):
        print([alpha[j]*Legendre[j]])
    #egendre[i] = Legendre[i]
    print(Legendre)
    ### Das Polynom muss nun noch normiert werden:
#    NormFaktor = . . . . . 
#   Legendre(i,1:i) = . . . . . .

Gauss-Quadratur
[]
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
i=1 j=0
q[1:1] = Legendreteil: []
alpha =  [ 0.]
[ 0.]
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0

### Wenig aussagekraeftige Ausgabewerte...

In [ ]:
print('Koeffizienten der Legendre-Polynome:')
Legendre

### Nullstellenberechnung: (liefert Stuetzstellen)

In [3]:
tau = zeros(N,N) # Speicher reservieren
for i = 1:N
    p = zeros(i+1,1)
    ### ACHTUNG: Die Zeilen aus der Matrix
    ### Legendre haben ein anderes Format, als fuer
    ### den Matlab internen roots-Befehl vorgesehen
    ### -> Umspeichern:
    for j = 1:i+1
        p(j) = . . . . . 
    end
    ### Nullstellenberechnung:
    r = roots( p )
    ### Nullstellen in Matrix tau ablegen:
    tau(i,1:i) = . . . . 
end

print('')
print('Stützstellen für die Gauss-Quadratur:')
tau
save( . . . . )

# Berechnung der Lagrange-Gewichte:
lambda=zeros(N,N)
for i=1:N # i: Anzahl der Stuetzstellen des Verfahrens
    # T: Vektor der Stützstellen
    T(1:i) = . . . .
    for j=1:i
        p    = zeros(i,1)
        # Starte mit p(t) = 1, d.h. p(1) = 1
        p(1) = 1
        
        # Durchlaufe alle Stuetzstellen
        for k = 1:i
            # Bei der Berechnung des j-ten Polynoms muessen alle
            # Stuetzstellen ausser der j-ten beruecksichtigt werden
            if ( . . . . )
                pold = p # Aktuelles Polynom zwischenspeichern
                # Koeffizienten von p um eins nach rechts
                # verschieben (entspricht Multiplikation mit t):
                for l=i:-1:2
                    p(l) = . . . .
                end
                # Der erste Koeffizient muss NULL sein:
                p(1) = 0
                # p_neu = ( t*p_alt - tau_k*p_alt )/ ( tau_j - tau_k )
                p = . . . . . 
            end
        end
        # Polynom konstruiert. Berechne Integral -> Lagrangegewicht
        lambda(i,j) = . . . . . 
    end
end
print('')
print('Gewichte:')
lambda
save( . . . . )

load('errorNC.mat')
# Auswertung des Integrals (ein Teilintervall):
for i = 1:N
    T   = zeros(i,1)
    for j = 1:i
        T(j) = Tmax*tau(i,j)
    end
    f   = funk(T)
    val = Tmax*lambda(i,1:i)*f
    print(sprintf('Approximation mit %2d Stützstellen: %22.14g, Fehler: %22.14g, Fehler_NC: %22.14g', i, val, Iexakt-val, errorNC(i)))
end

print('')
print('Berechnung mit mehreren Teilintervallen:')

SyntaxError: invalid syntax (<ipython-input-3-608bc9c8cd27>, line 7)

### Grafische Darstellung der Funktion sowie der Stützstellen

In [ ]:
n = 100
x = Tmin:(Tmax-Tmin)/n:Tmax
figure
plot(x,funk(x))
hold on

### Auswertung des Integrals

In [ ]:
# Auswertung des Integrals (mehrere Teilintervall):
Nint     = 5 # Anzahl der Teilintervalle
integral = 0.
order    = 4  # Anzahl der Stützstellen PRO TEILINTERVALL
h        = . . . . .  # Schrittweite
T        = zeros(order,1) # Vektor der Stuetzstellen im aktuellen Teilintervall
for k=0:Nint-1
    a = . . .  b = . . . # Intervallgrenzen

    for j = 1:order
        T(j) = a + h*tau(order,j)
    end
    f   = . . . .
    val = . . . .

    integral = integral + val
    
    plot(T,f,'*')
end
print(sprintf('Approximation mit %2d Teilintervallen mit je %2d Stützstellen: %22.14g, Fehler: %22.14g', Nint, order, integral, Iexakt-integral))

line(xlim,[0 0],'Color','r')