#   

In [1]:
import numpy as np
import numpy.linalg as la
from scipy.linalg import lu,lu_factor,lu_solve
from rum.basics import matprint, matprops
from rum.solve import thomas

## a)

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
matprops(A)

detA = 0.0
rgA = 2
symA = 
[[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]
skwA = 
[[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]]
trA = 15
lambda_i:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15] 
 u_i: 
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


#   

## a)

In [4]:
def vectornorm(v,p):
    d = np.size(v)
    
    if p == 1:
        return sum(v)
    
    elif p == np.inf:
        return max(v)
    
    elif p == 2:
        return (sum(x**2))**(1/2)
        
    else:
        n = 0
        for i in range(0,d):
             n = n + abs(v[i])**p
        return n**(1/p)

In [5]:
# Zufallsvektor erstellen
x = np.random.rand(5)

In [6]:
p_values = [1,np.inf,2,3.3,4]

print("Zufallsvektor: {}".format(x))
for p in p_values:
    print("p={}".format(p))      
    print(vectornorm(x,p))


Zufallsvektor: [0.82628867 0.24086434 0.97648585 0.68726138 0.69606939]
p=1
3.4269696243174135
p=inf
0.9764858459797536
p=2
1.6282303292868747
p=3.3
1.244641318380351
p=4
1.164131520345143


## b)

In [7]:
matrix = np.loadtxt('Blatt2_matrix.dat')
print ("Loaded {} matrix".format(np.shape(matrix)))

Loaded (10, 10) matrix


In [8]:
p_values=[1,2,np.inf]
for p in p_values:
    k = la.cond(matrix, p = p)
    print("p = {:3} --> k={} ".format(p, k))      

p =   1 --> k=93.80377097043943 
p =   2 --> k=46.273081094414565 
p = inf --> k=93.06720009548833 


#   
## a)

In [9]:
A = np.array([[1,2,0.5,0,-2],[-1,6,1.2,3.4,-0.1],[0.075,1,0.39,np.sqrt(3),0],[0.6,2/3,-0.41,1,1.07],[-0.2,-0.7,0.81,4,5]])
b = np.array([-5,3,0.9,1.42,np.sqrt(2)])
print("A:")
matprint(A)
print("b:")
print(b)

A:
    1         2    0.5        0    -2  
   -1         6    1.2      3.4  -0.1  
0.075         1   0.39  1.73205     0  
  0.6  0.666667  -0.41        1  1.07  
 -0.2      -0.7   0.81        4     5  
b:
[-5.          3.          0.9         1.42        1.41421356]


In [10]:
# Invertieren
print("Inverse:")
matprint(np.array(np.matrix(A).I))

Inverse:
 0.648301   -0.19462  -0.237071  0.351502      0.180206  
 0.102101   0.191965  -0.497615  0.211763  -0.000637387  
 0.791795  0.0274218  -0.702685  -1.00843      0.533071  
-0.265306  -0.108578    1.03314  0.089583     -0.127465  
   0.1242   0.101511  -0.791822  0.135406      0.222733  


In [11]:
# LUP-Zerlegung
lu_and_piv = lu_factor(A)
print(lu_and_piv)

(array([[ 1.        ,  2.        ,  0.5       ,  0.        , -2.        ],
       [-1.        ,  8.        ,  1.7       ,  3.4       , -2.1       ],
       [-0.2       , -0.0375    ,  0.97375   ,  4.1275    ,  4.52125   ],
       [ 0.6       , -0.06666667, -0.61275139,  3.75579803,  4.90040223],
       [ 0.075     ,  0.10625   ,  0.17650834,  0.17100563, -1.26290973]]), array([0, 1, 4, 3, 4], dtype=int32))


In [12]:
x = lu_solve(lu_and_piv,b)

In [13]:
print("Ax: {}".format(A.dot(x)))
print("b : {}".format(b))

Ax: [-5.          3.          0.9         1.42        1.41421356]
b : [-5.          3.          0.9         1.42        1.41421356]


## b)

In [14]:
def Tn(n):
    T = np.zeros([n,n])
    T[0,0] = 2
    T[1,0] = -1
    for i in range(1, n-1):
        T[i-1,i] = -1
        T[ i ,i] = 2
        T[i+1,i] = -1
    T[n-2,n-1] = -1
    T[n-1,n-1] = 2
    return T

for n in [3,10,50,500]:
    print("n={:3} -> k2 = {:.0f}".format(n, la.cond(Tn(n),p=np.inf)))

n=  3 -> k2 = 8
n= 10 -> k2 = 60
n= 50 -> k2 = 1300
n=500 -> k2 = 125500


In [15]:
b = np.array([2,3,4])
T = Tn(len(b))

print(lu_solve(lu_factor(T),b))
print(thomas(a=-1,b=2,c=-1, y=b))

[4. 6. 5.]
[4. 6. 5.]


In [16]:
%timeit lu_solve(lu_factor(T),b)

The slowest run took 17.48 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 27.4 µs per loop


In [17]:
%timeit thomas(a=-1,b=2,c=-1, y=b)

The slowest run took 4.70 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11.1 µs per loop
