# Übungsblatt 2

## Aufgabe 1

In [47]:
import numpy as np
import numpy.linalg as la
import scipy.linalg as scla

### a)

In [48]:
def matrixproperties(a):
    print("detA = " + str(la.det(A)))
    print("rgA = " + str(la.matrix_rank(A)))
    print("symA = \n" + str(1/2*(A + A.T)))
    print("skwA = \n" + str(1/2*(A - A.T)))
    print("trA = " + str(np.trace(A)))
    print("eigA = " + str(la.eig(A)))

In [49]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
matrixproperties(A)

detA = 0.0
rgA = 2
symA = 
[[ 1.  3.  5.]
 [ 3.  5.  7.]
 [ 5.  7.  9.]]
skwA = 
[[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]]
trA = 15
eigA = (array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


### b)

In [51]:
A[2,2] = 10
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [52]:
matrixproperties(A)

detA = -3.0
rgA = 3
symA = 
[[  1.   3.   5.]
 [  3.   5.   7.]
 [  5.   7.  10.]]
skwA = 
[[ 0. -1. -2.]
 [ 1.  0. -1.]
 [ 2.  1.  0.]]
trA = 16
eigA = (array([ 16.70749332,  -0.90574018,   0.19824686]), array([[-0.22351336, -0.86584578,  0.27829649],
       [-0.50394563,  0.0856512 , -0.8318468 ],
       [-0.83431444,  0.4929249 ,  0.48018951]]))


#### Die Schiefsymmetrischen Anteile sind unverändert.

## Aufgabe 2

### a)

In [53]:
def vectornorm(v,p):
    d = np.size(v)
    
    if p == 1:
        return sum(v)
    
    elif p == np.inf:
        return max(v)
    
    elif p == 2:
        return (sum(x**2))**(1/2)
        
    else:
        n = 0
        for i in range(0,d):
             n = n + abs(v[i])**p
        return n**(1/p)


In [54]:
x = np.random.rand(5)

In [55]:
print(x)
print(vectornorm(x,1))
print(vectornorm(x,np.inf))
print(vectornorm(x,2))
print(vectornorm(x,3.3))
print(vectornorm(x,4))

[ 0.22227714  0.8622473   0.12935201  0.04301711  0.57587061]
1.83276416598
0.862247300528
1.06915242406
0.928627530367
0.903189158362


### b)

In [56]:
matrix = np.loadtxt('matrix.dat')
print ("Loaded {} matrix".format(np.shape(matrix)))

Loaded (10, 10) matrix


In [57]:
print(la.cond(matrix,p=1))
print(la.cond(matrix,p=2))
print(la.cond(matrix,p=np.inf))

93.8037709704
46.2730810944
93.0672000955


## Aufgabe 3

In [63]:
from scipy.linalg import lu,lu_factor,lu_solve
A = np.array([[1,2,0.5,0,-2],[-1,6,1.2,3.4,-0.1],[0.075,1,0.39,np.sqrt(3),0],[0.6,2/3,-0.41,1,1.07],[-0.2,-0.7,0.81,4,5]])
P,L,U = lu(A)
print ("L:")
print (L)
print ("U:")
print (U)
print ("P:")
print (P)

L:
[[ 1.          0.          0.          0.          0.        ]
 [-1.          1.          0.          0.          0.        ]
 [-0.2        -0.0375      1.          0.          0.        ]
 [ 0.6        -0.06666667 -0.61275139  1.          0.        ]
 [ 0.075       0.10625     0.17650834  0.17100563  1.        ]]
U:
[[ 1.          2.          0.5         0.         -2.        ]
 [ 0.          8.          1.7         3.4        -2.1       ]
 [ 0.          0.          0.97375     4.1275      4.52125   ]
 [ 0.          0.          0.          3.75579803  4.90040223]
 [ 0.          0.          0.          0.         -1.26290973]]
P:
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]]


In [62]:
lu = lu_factor(A)
lu_solve(lu,v)

array([[-3.28474431],
       [-0.08266294],
       [-5.18722241],
       [ 1.87756357],
       [-0.5218407 ]])