In [1]:
import numpy as np
import scipy.linalg

## Aufgabe 1

### a) 

In [3]:
x = np.array(([1],[0],[3]))

In [4]:
y = np.array(([-1],[6],[0.5]))
print(y)

[[-1. ]
 [ 6. ]
 [ 0.5]]


In [11]:
print (y.T)

[[-1.   6.   0.5]]


### b)

In [6]:
x.T.dot(y)

array([[ 0.5]])

In [7]:
x.dot(y.T)

array([[ -1. ,   6. ,   0.5],
       [  0. ,   0. ,   0. ],
       [ -3. ,  18. ,   1.5]])

In [14]:
y.dot(x.T)

array([[ -1. ,   0. ,  -3. ],
       [  6. ,   0. ,  18. ],
       [  0.5,   0. ,   1.5]])

In [15]:
x*y

array([[-1. ],
       [ 0. ],
       [ 1.5]])

In [16]:
x/y

array([[-1.],
       [ 0.],
       [ 6.]])

In [17]:
x+y

array([[ 0. ],
       [ 6. ],
       [ 3.5]])

In [18]:
x-y

array([[ 2. ],
       [-6. ],
       [ 2.5]])

### c)

In [24]:
n = np.zeros([3,4])
print(n)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [26]:
n = 5
i = np.eye(n)
print (i)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


### d)

In [48]:
m = 3
R = np.random.rand(m,m)
#print(R)
Z = 2*R-1
print(Z)

[[ 0.9301749  -0.89106294  0.5730926 ]
 [-0.35772533 -0.72255756 -0.46317588]
 [ 0.75510436 -0.68052812 -0.64754204]]


### e)

In [62]:
from math import sqrt
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[-1,0.5,1.5],[-7,2,1],[1,0.4,12]])
C = np.array([[0.1,2.4,sqrt(2)],[123,-8,2/7],[0.25,1,2]])
print (A,B,C,sep='\n')

[[1 2 3]
 [4 5 6]]
[[ -1.    0.5   1.5]
 [ -7.    2.    1. ]
 [  1.    0.4  12. ]]
[[  1.00000000e-01   2.40000000e+00   1.41421356e+00]
 [  1.23000000e+02  -8.00000000e+00   2.85714286e-01]
 [  2.50000000e-01   1.00000000e+00   2.00000000e+00]]


### f)

In [63]:
A.dot(B)

array([[-12. ,   5.7,  39.5],
       [-33. ,  14.4,  83. ]])

In [64]:
B.dot(A.T)

array([[  4.5,   7.5],
       [  0. , -12. ],
       [ 37.8,  78. ]])

In [67]:
B-C

array([[ -1.10000000e+00,  -1.90000000e+00,   8.57864376e-02],
       [ -1.30000000e+02,   1.00000000e+01,   7.14285714e-01],
       [  7.50000000e-01,  -6.00000000e-01,   1.00000000e+01]])

## Aufgabe 2

### a)

In [72]:
x = np.zeros(8)
for i in range(0,8):
    x[i] = i

In [70]:
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.]


### b)

In [77]:
m = 3
Z = np.zeros([m,m])
for i in range(0,m):
    for j in range(0,m):
        Z[i,j] = np.random.rand(1)*2 - 1

In [78]:
print(Z)

[[-0.60378319  0.29173825 -0.48808007]
 [-0.74664058 -0.30561469 -0.21213239]
 [ 0.69824167  0.57373414  0.31891002]]


## Aufgabe 3

### a)

In [82]:
a = 0
b = 4
x = (b-a) * np.random.rand(20) + a

In [83]:
print(x)


[ 3.30263961  2.38242193  1.34482418  1.21811554  3.15326622  0.36476953
  0.13391808  0.05769647  3.64725109  2.82873042  0.50015602  2.57420057
  2.73761865  3.85914903  1.07624393  3.4494074   3.29344307  2.5189559
  3.01503014  0.994618  ]


In [87]:
alpha = 0.1
y = np.exp(alpha*x)

In [88]:
print(y)

[ 1.39133534  1.2690165   1.14394455  1.12954122  1.37070694  1.0371504
  1.01348188  1.00578632  1.44011808  1.32693669  1.0512875   1.29358839
  1.31490164  1.47095949  1.11362938  1.41190625  1.39005638  1.28646171
  1.35188919  1.10457628]


### b)


In [91]:
D = np.cos(A)

In [95]:
print(A)
print(D)

[[1 2 3]
 [4 5 6]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


## Hausaufabe

In [116]:
k = 1000
count = 0
found = []
end = False
while not end:
    x = np.random.rand()
    if x > 0.75:
        found.append(x)
    if len(found) >= k:
        end = True
        print ("Took {} iterations.".format(count))
    count = count + 1

Took 4103 iterations.
