In [97]:
import numpy as np
import scipy.linalg as la

### Aufgabe 3

### a)

In [98]:
A = np.array([[1,2,0.5,0,-2],[-1,6,1.2,3.4,-0.1],[0.075,1,0.39,np.sqrt(3),0],[0.6,2/3,-0.41,1,1.07],[-0.2,-0.7,0.81,4,5]])
b = np.array([[-5],[3],[0.9],[1.42],[np.sqrt(2)]])

In [99]:
print ('A = \n' + str(A))
print ('b = \n' + str(b)) 

A = 
[[ 1.          2.          0.5         0.         -2.        ]
 [-1.          6.          1.2         3.4        -0.1       ]
 [ 0.075       1.          0.39        1.73205081  0.        ]
 [ 0.6         0.66666667 -0.41        1.          1.07      ]
 [-0.2        -0.7         0.81        4.          5.        ]]
b = 
[[-5.        ]
 [ 3.        ]
 [ 0.9       ]
 [ 1.42      ]
 [ 1.41421356]]


#### Matrixinversion

In [100]:
A = np.array([[1,2,0.5,0,-2],[-1,6,1.2,3.4,-0.1],[0.075,1,0.39,np.sqrt(3),0],[0.6,2/3,-0.41,1,1.07],[-0.2,-0.7,0.81,4,5]])
x = Ainv.dot(b)
print ('x = \n' + str(x))

x = 
[[-3.28474431]
 [-0.08266294]
 [-5.18722241]
 [ 1.87756357]
 [-0.5218407 ]]


In [101]:
#Verifizieren
print ('A*x = \n' + str(A.dot(x)))

A*x = 
[[-5.        ]
 [ 3.        ]
 [ 0.9       ]
 [ 1.42      ]
 [ 1.41421356]]


#### LU-Zerlegung

In [135]:
n = A.shape[1] #vertical size of the matrix
L = np.eye(n)
U = np.zeros([n,n])
y = np.zeros(n)
# y muss explizit zu einem Spaltenvektor gamacht werden
y.shape = (n,1)

In [136]:
print ('L = \n' + str(L))
print ('U = \n' + str(U))

L = 
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
U = 
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


##### L und U bestimmen

Matrix ist invertierbar --> keine Permutation notwendig!

In [172]:
for j in range(0,n):
    # for each column
    U[0][j] = A[0][j]
    for i in range(j+1):
        U[i][j] = A[i][j] - sum([L[i][k]*U[k][j] for k in range(i)])
    for i in range(j+1,n):
        L[i][j] = (A[i][j] - sum([L[i][k]*U[k][j] for k in range(j)]))/U[j][j]

In [173]:
print ("L:")
print (L)
print ("U:")
print (U)

L:
[[ 1.          0.          0.          0.          0.        ]
 [-1.          1.          0.          0.          0.        ]
 [ 0.075       0.10625     1.          0.          0.        ]
 [ 0.6        -0.06666667 -3.47151515  1.          0.        ]
 [-0.2        -0.0375      5.66545455 -0.60792863  1.        ]]
U:
[[ 1.          2.          0.5         0.         -2.        ]
 [ 0.          8.          1.7         3.4        -2.1       ]
 [ 0.          0.          0.171875    1.37080081  0.373125  ]
 [ 0.          0.          0.          5.98542244  3.42530909]
 [ 0.          0.          0.          0.          4.48967074]]


##### Lösen Ly=b und Ux=y

In [174]:
# y bestimmen aus L und b
for i in range(n):
    y[i] = b[i] - sum([y[k]*L[i][k] for k in range(i)])
# x bestimmen aus b und U
x = np.zeros(n)
x.shape = (n,1)
for i in range(n-1,-1,-1):
    x[i] = (y[i] -  sum([U[i][k]*x[k] for k in range(n-1,i,-1)]))/U[i][i]
print(x)

[[-3.28474431]
 [-0.08266294]
 [-5.18722241]
 [ 1.87756357]
 [-0.5218407 ]]


##### Vergleich mit scipy.lingalg.lu

In [176]:
from scipy.linalg import lu,lu_factor,lu_solve
A = np.array([[1,2,0.5,0,-2],[-1,6,1.2,3.4,-0.1],[0.075,1,0.39,np.sqrt(3),0],[0.6,2/3,-0.41,1,1.07],[-0.2,-0.7,0.81,4,5]])
P,L,U = lu(A) # nutzt permutation matrix
print ("L:")
print (L)
print ("U:")
print (U)
print ("P:")
print (P)
lu = lu_factor(A)
lu_solve(lu,b)

L:
[[ 1.          0.          0.          0.          0.        ]
 [-1.          1.          0.          0.          0.        ]
 [-0.2        -0.0375      1.          0.          0.        ]
 [ 0.6        -0.06666667 -0.61275139  1.          0.        ]
 [ 0.075       0.10625     0.17650834  0.17100563  1.        ]]
U:
[[ 1.          2.          0.5         0.         -2.        ]
 [ 0.          8.          1.7         3.4        -2.1       ]
 [ 0.          0.          0.97375     4.1275      4.52125   ]
 [ 0.          0.          0.          3.75579803  4.90040223]
 [ 0.          0.          0.          0.         -1.26290973]]
P:
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.]]


array([[-3.28474431],
       [-0.08266294],
       [-5.18722241],
       [ 1.87756357],
       [-0.5218407 ]])

### b) 
#### Tridiagonale Matrix

In [107]:
def Tmatrix(n):
    T=np.zeros([n,n])
    T[0,0] = 2 # Top left separately
    for i in range(1,n):
        T[i,i] = 2
        T[i-1,i] = -1
        T[i,i-1] = -1
    return (T)

In [108]:
print(Tmatrix(5))

[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]


In [109]:
for n in [3,10,50,500]:
    T = Tmatrix(n)
    k2 = np.linalg.cond(T,2)
    print("K2 für n = {} is {}".format(n,k2))

K2 für n = 3 is 5.828427124746189
K2 für n = 10 is 48.37415007870823
K2 für n = 50 is 1053.4789912001029
K2 für n = 500 is 101726.20699563753


##### Was folgt daraus bei einer Rechengenauigkeit von ≈ 10<sup>−16</sup> (das entspricht double-Precision auf bestimmten Maschinen)?
TODO

In [228]:
def TDMAsolver(T,y):
    n = T.shape[0]
    x=np.zeros(n)

    #make some copies
    Tc = np.array(T)
    yc = np.array(y)
    
    #first values directly
    Tc[0][1] = T[0][1]/T[0][0]
    yc[0] = y[0]/T[0][0]
        
    #Vorwaertseinsetzen
    for i in range(1,n-1):
        Tc[i][i+1] = T[i][i+1]/(T[i][i]-Tc[i-1][i]*T[i][i-1])
    for i in range(1,n):
        yc[i] = (y[i]-yc[i-1]*T[i][i-1])/(T[i][i]-Tc[i-1][i]*T[i][i-1])
        
    #yc[n-1] = (y[n-1]-yc[n-2]*T[n-2][n-1])/(T[n-1][n-1]-Tc[n-2][n-1]*T[i][i-1])
    
    #Rueckwaertseinsetzen
    x[n-1] = yc[n-1]
    for i in reversed(range(0,n-1)):
        x[i] = yc[i] - Tc[i][i+1]*x[i+1]
    
    x.shape = (n,1)
    return x

In [229]:
b = np.array([[-5],[3],[0.9],[1.42],[np.sqrt(2)]])
x = TDMAsolver(Tmatrix(5),b)
print ("T.dot(x) is")
print (T.dot(x))
print ("and b is ")
print (b)

T.dot(x) is
[[-5.        ]
 [ 3.        ]
 [ 0.9       ]
 [ 1.42      ]
 [ 1.41421356]]
and b is 
[[-5.        ]
 [ 3.        ]
 [ 0.9       ]
 [ 1.42      ]
 [ 1.41421356]]
